# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4604c1a6-f6fd-4454-b3f7-f3c0ac11891c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4604c1a6-f6fd-4454-b3f7-f3c0ac11891c".device = "/dev/disk/by-uuid/4604c1a6-f6fd-4454-b3f7-f3c0ac11891c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/356A-C03D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a0c0a1ea-39a6-496f-b5c4-5665a0c24721"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
